image: jekyll/jekyll
stages:
  - build
  - deploy
variables:
  AWS_DEFAULT_REGION: us-east-1
  BUCKET_NAME: www.jacobparry.ca

build-site:
  stage: build
  script:
    - jekyll build
  artifacts:
    paths:
      - _site/

deploy:
  image: "python:latest"
  stage: deploy
  dependencies:
    - build-site
  before_script:
    - pip install awscli
  script:
    - aws s3 cp _site/ s3://${BUCKET_NAME}/ --recursive
  environment:
    name: Live
    url: https://www.jacobparry.ca/