timezone: America/Toronto
encoding: utf-8
highlighter: pygments
baseurl: https://threadproc.io
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Rakefile']
markdown: kramdown
permalink: /:year/:title.html
assets:
  compress:
    css: sass
