source 'https://rubygems.org'
#ruby '2.1.5'
gem 'bundler'
gem 'jekyll'
gem 'rack', ">= 2.1.4"
gem 'rack-jekyll', git: 'https://github.com/adaoraul/rack-jekyll.git'
gem 'jekyll-assets'
gem 'kramdown'
gem 'pygmentize'
gem 'compass'
gem 'rack-contrib'
gem 'rack-rewrite'
gem 'puma'
